### ISSUE TITLE
Filter by player name before sending requests

### ISSUE THREAD

**Issue by oldherl** [Copay/caraoke-plasmoid#4]
For example, I use only exaile or amarok to play music, so I would like to send only requests from those players.
Other players are for playing videos, (movie etc) and sending those requests would be useless.

**Comment by Sinofine** [comment]
it can be done by filtering `mpris2Model.currentPlayer?.identity`.

I may do that in recent days.

**Comment by Sinofine** [comment]
Maybe we'd better provide a text field in configuration for a RegExp string to test the identity?
like this: `exaile|amarok|g4music`

**Comment by oldherl** [comment]
Yes, it should be configurable by the user. I don't mind what UI widget to be used, a simple text field containing a comma-separated-list or RegExp are both acceptable. Or a list-like widget.

**Comment by Sinofine** [comment]
Seems that some music player would use its local name as identity such as "无缺音乐" rather than "Gapless" or "g4music".

So I suggest use its `objectName`. You can check that in mpris inspection tools like `d-spy`.

It looks like `org.mpris.MediaPlayer2.(objectName)`.
